[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pinnicle-antarctica"
version = "0.1.0"
description = "Python client and mesh generator for PINNICLE Antarctica data product"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "Kevin Shionalyn"}
]
dependencies = [
    "torch",
    "numpy",
    "xarray",
    "netcdf4"
]

[project.scripts]
pinnicle-antarctica = "client.mesh_cli:main"

[tool.setuptools.packages.find]
where = ["."]
